#!/usr/bin/env bash
# Backup and compress MySQL databases

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
backup_file_name="$day-$month-$year.tar.gz"
mysql_user="root"

# Backup databases
mysqldump --all-databases -u "$mysql_user" --password="$1" > backup.sql

# Compress backup
tar -czvf "$backup_file_name" backup.sql
