#!/usr/bin/env bash

SCRIPT_PATH="./manage_my_process"

case "$1" in
    start)
        if pgrep -f "$SCRIPT_PATH" >/dev/null; then
            echo "manage_my_process is already running."
        else
            $SCRIPT_PATH &
            echo "$!" > /var/run/my_process.pid
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill "$pid" && rm -f /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
