#!/usr/bin/env bash
# Invicible self to infinity and beyond

vibranium_shield() {
    echo "I am invincible!!!"
}

# Set the terminate function to be executed on SIGTERM
trap 'vibranium_shield' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
