#!/usr/bin/env bash
# Script to display "Best School" 10 times using a for loop

# Start of the for loop: Initialize i to 1, loop as long as i is less than or equal to 10, increment i in each iteration
for ((i = 1; i <= 10; i++))
do
    # Inside the loop: Print "Best School" to the standard output
    echo "Best School"
done

