#!/usr/bin/env bash
# This script displays the username, user id,
# and home directory path for each user in /etc/passwd.

myfile="/etc/passwd"
while IFS=: read -r username uid _ home _ _; do
  echo "$username:$uid:$home"
done < "$myfile"
