#!/usr/bin/env bash
# Script to display information about users from /etc/passwd using a while loop and IFS

# Specify the file path
passwd_file="/etc/passwd"

# Read each line from the file
while IFS=: read -r username password uid gid info home shell
do
    # Display user information using the specified format
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $info"
    echo
done < "$passwd_file"

