#!/usr/bin/env bash
# Script to display information about users from /etc/passwd using a while loop and IFS

# Specify the file path
passwd_file="/etc/passwd"

# Read each line from the file
while IFS=: read -r username x uid gid info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"

done < "$passwd_file"

