#!/usr/bin/env bash
# Script to display "Best School" 10 times using a while loop

# Initialize the counter variable i to 1
i=1

# Start of the while loop: Continue looping as long as i is less than or equal to 10
while [ $i -le 10 ]
do
    # Inside the loop: Print "Best School" to the standard output
    echo "Best School"

    # Increment the counter variable i
    ((i++))
done

