#!/usr/bin/env bash
# A script that loops through numbers 1 to 10 using a while loop.

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
