#!/usr/bin/env bash
# Script to loop through 1 to 10 using a while loop

# Initialize the counter variable i to 1
i=1

# Start of the while loop: Continue looping until i is greater than 10
while [ $i -le 10 ]
do
    # Inside the loop: Check if i is equal to 4
    if [ $i -eq 4 ]
    then
        # If true, print "bad luck" to the standard output
        echo "bad luck"

    # Check if i is equal to 8
    elif [ $i -eq 8 ]
    then
        # If true, print "good luck" to the standard output
        echo "good luck"

    # If neither condition is true, execute the following block
    else
        # Print "Best School" to the standard output
        echo "Best School"
    fi

    # Increment the counter variable i
    ((i++))
done

