#!/usr/bin/env bash
# This Bash script displays the time for
# 12 hours and 59 minutes.
# It iterates through hours from 0 to 12 and
# minutes from 1 to 59 for each hour.

hr=0

while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    ((min++))
  done
  ((hr++))
done
