#!/usr/bin/env bash
# The script configures an Ubunto server DNS records

# Backup the original hosts file
cp /etc/hosts /etc/hosts.backup

# Configure localhost and facebook.com
echo "127.0.0.2       localhost" > /etc/hosts
echo "8.8.8.8         facebook.com" >> /etc/hosts

